twig:
<<<<<<< HEAD
    file_name_pattern: '*.twig'
=======
    default_path: '%kernel.project_dir%/templates'
>>>>>>> 78136c9 (Upload projet ECF Symfony)

when@test:
    twig:
        strict_variables: true
