when@dev:
    web_profiler:
<<<<<<< HEAD
        toolbar: true

    framework:
        profiler:
            collect_serializer_data: true

when@test:
=======
        toolbar: false
        intercept_redirects: false

    framework:
        profiler:
            only_exceptions: false
            collect_serializer_data: true

when@test:
    web_profiler:
        toolbar: false
        intercept_redirects: false

>>>>>>> 78136c9 (Upload projet ECF Symfony)
    framework:
        profiler: { collect: false }
